### PR TITLE
fix importRegex

### PR DESCRIPTION
**Pull request by pravdomil**
copy paste bug

### CODE REVIEW

**Comment by mathieudutour** [comment]
good catch!

**Comment by pravdomil** [comment]
well I'm rewriting it to typescript so those issues show up

**Comment by mathieudutour** [comment]
oh, just so you know, I won't accept a PR rewriting everything in TS. I do like typescript but sometime not having a build step is nice

**Comment by pravdomil** [comment]
yes, there is ~500ms delay after each save, but the advantages of code completion and type checking compensate that

btw: https://github.com/BohemianCoding/SketchAPI/pull/66

**Comment by mathieudutour** [comment]
Again, to clear all confusion, I will not accept a PR rewriting everything in typescript. Not that I don’t like typescript, I actually have a pretty big project in typescript: https://github.com/kactus-io/kactus but there are some cases where it doesn’t fit. This is one of them. 

You cannot come to a project and rewrite everything in another language (even if the language is a superset) without talking to the maintainers first. And I’m confident that in 99% of the cases, the answer will be no. 

I am thankful of your willgness to contribute and fix bugs, but you cannot force a change like that. Feel free to create your own project in typescript.

**Comment by pravdomil** [comment]
ok

**Comment by pravdomil** [comment]
@mathieudutour 
>  I do like typescript but sometime not having a build step is nice

you can use <a href="https://github.com/TypeStrong/ts-node">ts-node</a> to run ts files directly in node.js

**Comment by mathieudutour** [comment]
> Again, to clear all confusion, I will not accept a PR rewriting everything in typescript. Not that I don’t like typescript, I actually have a pretty big project in typescript: https://github.com/kactus-io/kactus but there are some cases where it doesn’t fit. This is one of them.

**Pull request merged**
